n = input('Digite alguma coisa: ')
print('O tipo primitivo desse valor é: ', type(n))
print('Só tem espaço? ', n.isspace())
print('É um número? ', n.isalnum())
print('É um alfabético? ', n.isalpha())
print('É um alfanumérico? ', n.isspace())
print('Está em maiúscula? ', n.isupper())
print('Está em minúscula? ', n.islower())
print('Está em capitalizada? (maiuscula e minuscula)? ', n.istitle())
